name: InfiniThing
description: A plugin that provides players with an item that has infinite uses, but at a cost.
version: 1.1
author: TehBossCat
main: me.tehbosscat.infinithing.Main

commands:
  infini:
    aliases: [inf]
    usage: /<command> [bucket|pearl]
    description: Spawns a bucket or pearl if the parameter is entered. If no parameter is entered, opens up a menu to let the player spawn one or the other.

permissions:
  infini.bucket.craft:
    description: Allows a player to craft an InfiniBucket.
    default: notop
  infini.bucket.spawn:
    description: Allows a player to spawn an InfiniBucket.
    default: op
  infini.bucket.use:
    description: Allows a player to use an InfiniBucket.
    default: op
  infini.bucket.fill:
    description: Allows a player to fill an InfiniBucket.
    default: op

  infini.pearl.craft:
    description: Allows a player to craft an InfiniPearl.
    default: notop
  infini.pearl.spawn:
    description: Allows a player to spawn an InfiniBucket.
    default: op
  infini.pearl.use:
     description: Allows a player to use an InfiniBucket.
     default: op
